spring:
  application:
    name: kotlin-spring-jwt-learning

  datasource:
    url: jdbc:h2:mem:${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}  # 15 minutes for access token
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}  # 7 days for refresh token